version: 2.1

executors:
  mac:
    working_directory: '~/go/src/github.com/influxdata/telegraf'
    resource_class: medium
    macos:
      xcode: 13.2.0
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      GOFLAGS: -p=8

commands:
  test-go:
    parameters:
      os:
        type: string
        default: "linux"
      arch:
        type: string
        default: "amd64"
      gotestsum:
        type: string
        default: "gotestsum"
      cache_version:
        type: string
        default: "v3"
    steps:
      - checkout
      - restore_cache:
          key: darwin-go-<< parameters.cache_version >>-{{ checksum "go.sum" }}
      - run: 'sh ./scripts/installgo_mac.sh'
      - run: mkdir -p test-results
      - run: ./scripts/install_gotestsum.sh << parameters.os >> << parameters.gotestsum >>
      - unless:
          condition:
            equal: [ "386", << parameters.arch >> ]
          steps:
            - run: echo 'export RACE="-race"' >> $BASH_ENV
      - run: |
          GOARCH=<< parameters.arch >> ./<< parameters.gotestsum >> --junitfile test-results/gotestsum-report.xml -- ${RACE} -short ./...
      - store_test_results:
          path: test-results
      - save_cache:
          name: 'Saving cache'
          key: darwin-go-<< parameters.cache_version >>-{{ checksum "go.sum" }}
          paths:
            - '/go/src/github.com/influxdata/telegraf/gotestsum'
            - '/usr/local/Cellar/go'
            - '/usr/local/bin/go'
            - '/usr/local/bin/gofmt'

jobs:
  test-go-mac:
    executor: mac
    steps:
      - test-go:
          os: darwin

workflows:
  version: 2
  check:
    jobs:
      - 'test-go-mac':
          filters:
            tags: # only runs on tags if you specify this filter
              only: /.*/
